// Historical test source; update old chapter/node expectations before use.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('http'),fs=require('fs'),path=require('path');
const root=path.resolve(process.env.GAME_DIR||path.resolve(__dirname,'../..')),out=__dirname;let browser;
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(f===root)f=path.join(root,'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const errors=[];
for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:width===1440?900:width===768?1024:844},reducedMotion:'no-preference'});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle'});
const ready=()=>page.waitForFunction(()=>[...document.querySelectorAll('img')].filter(i=>i.getClientRects().length).every(i=>i.complete&&i.naturalWidth>0));
async function show(c,query){await ready();await page.evaluate(({c,query})=>{review=false;mainState=null;const idx=CHAPTERS[c].nodes.findIndex(n=>query.kind?n.kind===query.kind:n.bg===query.bg);if(idx<0)throw Error('missing node');state={...fresh(),c,n:idx,unlocked:c,gate:false};state.checkpoints[c]=checkpoint();render();stopTyping();},{c,query});await ready();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
for(const c of [4,5]){for(let food=0;food<3;food++){await show(c,{kind:'meal'});await page.locator('[data-food="'+food+'"]').click();await page.locator('.meal-plate').scrollIntoViewIfNeeded();assert.equal(await page.locator('.food-piece').count(),3);assert.equal(await page.locator('.eat-bite').textContent(),'吃一口');await page.click('.eat-bite');assert.equal(await page.locator('.eat-bite').textContent(),'正在吃…');assert.equal(await page.locator('.eat-bite').evaluate(e=>getComputedStyle(e).opacity),'1');assert.equal(await page.locator('.being-eaten').evaluate(e=>getComputedStyle(e).animationName),'eatBite');if(food===0)await page.screenshot({path:path.join(out,'meal-animation-'+c+'-'+width+'.webp')});await page.waitForFunction(()=>!document.querySelector('.eat-bite')?.disabled);assert.equal(await page.locator('.food-piece').count(),2);
assert.equal(await page.locator('.food-piece').count(),2);
for(let bite=0;bite<2;bite++){await page.click('.eat-bite');await page.waitForFunction(()=>!document.querySelector('.eat-bite')?.disabled);}assert.equal(await page.locator('.food-piece').count(),0);assert(await page.locator('.plate-empty').isVisible());if(food===0)await page.screenshot({path:path.join(out,'empty-plate-'+c+'-'+width+'.webp')});await page.click('.meal-finish');assert(await page.evaluate(()=>prog().done));}}
await show(2,{kind:'archive'});await page.fill('#anniversaryInput','0230');await page.click('.archive-lock');assert(!await page.evaluate(()=>prog().locked));await page.fill('#anniversaryInput','0920');await page.click('.archive-lock');assert((await page.locator('.anniversary-note').textContent()).includes('09 月 20'));await page.fill('#archivePassword','0920');await page.click('.archive-unlock');assert.equal(await page.locator('.letter-paper p').count(),7);await page.locator('.letter-paper').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'long-letter-'+width+'.webp')});await page.locator('.letter-paper p').last().scrollIntoViewIfNeeded();assert(await page.locator('.letter-paper p').last().isVisible());await page.locator('.task-next').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'letter-end-'+width+'.webp')});await page.click('.task-next');assert(await page.locator('#task').isHidden());const expectedLetterLine='信写完又读了一遍。我把“谢谢.zip”留好，合上电脑。还给他的时候，我只轻轻说了一句：“里面有个文件留给你，密码是我们第一次见面的日子。”';await page.waitForFunction(t=>document.querySelector('#lineText').textContent===t,expectedLetterLine);assert(!await page.locator('.letter-paper').isVisible());
for(const [bg,name] of [['photo-ball-photo','formal-photo'],['photo-ball','party-dance'],['photo-ball-walk','two-am-walk']]){await show(5,{bg});assert.equal(await page.locator('#sceneImage').getAttribute('data-bg'),bg);await page.screenshot({path:path.join(out,name+'-'+width+'.webp')});await page.reload({waitUntil:'networkidle'});await page.click('#continueBtn');await ready();assert.equal(await page.locator('#sceneImage').getAttribute('data-bg'),bg);}
await page.close();}
assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',viewports:[1440,768,390],foodsTested:6,animation:'eatBite verified and plates empty after 3 bites',letter:'custom date, invalid date rejection, full 7-paragraph letter',scenes:'formal photo, party dance, 02:00 walk, refresh continuity',errors},null,2));})().then(async()=>{await browser.close();server.close();}).catch(async e=>{console.error(e);if(browser)await browser.close();server.close();process.exitCode=1;});
