// Historical test source; update old chapter/node expectations before use.
'use strict';
const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=fs.realpathSync(process.env.GAME_DIR||path.resolve(__dirname,'../..')),out=__dirname,errors=[],taskSeen=new Set(),choiceSeen=new Set(),chaptersSeen=new Set(),checks=[];
const server=http.createServer((req,res)=>{const raw=decodeURIComponent(req.url.split('?')[0]);let p=path.resolve(root,'.'+raw);if(p===root)p=path.join(root,'index.html');if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(p,(e,d)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'})[path.extname(p)]||'application/octet-stream');res.end(d);});});
let browser;
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});page.on('requestfailed',r=>errors.push(r.url()+' '+r.failure()?.errorText));const base='http://127.0.0.1:'+server.address().port;
const snap=()=>page.evaluate(()=>JSON.parse(JSON.stringify({state,node:current(),p:prog(),k:key()})));
async function ready(){await page.waitForFunction(()=>{const i=document.querySelector('#sceneImage');return i.complete&&i.naturalWidth>0;});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal overflow');}
async function resume(){await ready();const s=await snap();await page.reload({waitUntil:'networkidle'});await page.click('#continueBtn');await ready();const a=await snap();assert.deepEqual(a.state,s.state,'exact save resume');}
async function restart(){await ready();await page.click('#replayBtn');await page.click('.restart-confirm');await ready();}
async function screenshot(name){await ready();await page.screenshot({path:path.join(out,name+'.webp')});}
const taskResumed=new Set(),chatResumed=new Set();
async function solve(){let info=await snap(),{node:n,k}=info;taskSeen.add(k);
if(info.p.done){await page.click('.task-next');return;}
if(n.photo&&n.kind!=='focus'){await page.waitForFunction(()=>document.querySelector('.puzzle-photo')?.complete&&document.querySelector('.puzzle-photo').naturalWidth>0);assert((await page.locator('.puzzle-photo').getAttribute('src')).includes(n.photo+'.webp'));if(n.photo==='photo-toy')await screenshot('toy-puzzle-'+(await page.viewportSize()).width);if(n.photo==='photo-airport-wait')await screenshot('airport-pickup-'+(await page.viewportSize()).width);if(n.photo==='photo-boarding-pass')await screenshot('boarding-pass-'+(await page.viewportSize()).width);}
 if(n.kind==='clue'){const wrong=n.options.findIndex(x=>!x.correct),correct=n.options.findIndex(x=>x.correct);await page.locator('[data-answer="'+wrong+'"]').click();assert(!(await snap()).p.done);assert(await page.locator('.task-feedback').isVisible());await page.locator('[data-answer="'+correct+'"]').click();}
else if(n.kind==='connect'){await page.click('.connect-btn');}
else if(n.steps){if((info.p.i||0)===0){await page.locator('[data-step="'+(n.steps.length-1)+'"]').click();assert.equal((await snap()).p.i,0);assert(await page.locator('.task-feedback').isVisible());if(n.kind==='pdf'){await page.click('.wrong-option');assert(!(await snap()).p.done);await screenshot('pdf-puzzle-'+(await page.viewportSize()).width);}}
while(!(info=await snap()).p.done){await page.locator('[data-step="'+info.p.i+'"]').click();if(!taskResumed.has(k)){await resume();taskResumed.add(k);}}}
else if(n.kind==='focus'){await page.waitForFunction(()=>document.querySelector('.focus-preview img')?.complete&&document.querySelector('.focus-preview img').naturalWidth>0);assert((await page.locator('.focus-preview img').getAttribute('src')).includes(n.photo+'.webp'));await page.click('.shutter');assert(!(await snap()).p.done);await page.locator('#focusRange').evaluate((input,target)=>{input.value=target;input.dispatchEvent(new Event('input',{bubbles:true}));},n.target);assert.equal((await snap()).p.value,n.target);await resume();await screenshot('focus-puzzle');await page.click('.shutter');}
else if(n.kind==='pin'){await page.fill('#pinInput','0'.repeat(n.length));const s=await snap();await page.locator('#pinInput').press('Enter');assert.equal((await snap()).k,s.k,'enter in input must not skip');await page.click('.pin-submit');assert(!(await snap()).p.done);await page.click('.pin-hint');assert((await page.locator('.task-feedback').textContent()).includes(n.hint));await page.fill('#pinInput',n.code);await resume();await page.click('.pin-submit');}
else if(n.items){if(n.kind==='memories'&&!info.p.found?.length){await page.locator('[data-memory="'+n.items[n.items.length-1].id+'"]').click();assert.equal((await snap()).p.found.length,0,'memory order rejects last first');}for(const item of n.items){if(!(await snap()).p.found?.includes(item.id)){await page.locator('[data-memory="'+item.id+'"]').click();if(n.kind==='memories'){await ready();assert.equal(await page.locator('#sceneImage').getAttribute('data-bg'),item.bg);await resume();assert.equal(await page.locator('#sceneImage').getAttribute('data-bg'),item.bg);}else if(!taskResumed.has(k)){await resume();taskResumed.add(k);}}}await page.click('.collect-finish');}
else if(n.kind==='archive'){
await page.fill('#anniversaryInput','1332');await page.click('.archive-lock');assert(!(await snap()).p.locked);await page.fill('#anniversaryInput','1012');await resume();await page.click('.archive-lock');await page.fill('#archivePassword','0000');await page.locator('#archivePassword').press('Enter');assert.equal((await snap()).k,k);await page.click('.archive-unlock');assert(!(await snap()).p.done);await page.fill('#archivePassword','1012');await resume();await page.click('.archive-unlock');assert((await page.locator('.letter-paper').textContent()).length>650);await screenshot('thank-letter-'+(await page.viewportSize()).width);await resume();assert.equal(await page.locator('.letter-paper p').count(),7);
}
else if(n.kind==='meal'){
await page.locator('[data-food="0"]').click();await page.click('.eat-bite');await page.waitForFunction(()=>!document.querySelector('.eat-bite')?.disabled);assert.equal((await snap()).p.bites,1);await resume();await screenshot(n.photo+'-'+(await page.viewportSize()).width);while((await snap()).p.bites<3){await page.click('.eat-bite');await page.waitForFunction(()=>!document.querySelector('.eat-bite')?.disabled);}assert.equal(await page.locator('.food-piece').count(),0);await page.click('.meal-finish');
}
else throw Error('Unknown task '+n.kind);
assert((await snap()).p.done,'task completed '+k);await page.click('.task-next');}
async function step(route,early=false,cancel=false){await ready();let {state:s,node:n,p,k}=await snap();chaptersSeen.add(s.c);if(s.ended)return false;if(s.gate){await page.click('.gate-start');return true;}
if(n.type==='line'){if(s.c===0&&s.n===0){await screenshot('dialogue-'+(await page.viewportSize()).width);await page.locator('body').evaluate(e=>{e.tabIndex=-1;e.focus();});await page.keyboard.press('Space');assert.equal((await snap()).state.n,1);}else await page.click('#nextBtn');}
else if(n.type==='choice'){if(p.selected===undefined){const i=s.c===0?(early?1:0):route;choiceSeen.add(k+':'+i);if(s.c===0)await screenshot('choice-'+(await page.viewportSize()).width);await page.locator('body').evaluate(e=>{e.tabIndex=-1;e.focus();});await page.keyboard.press('Space');assert.equal((await snap()).k,k);await page.locator('.choice').nth(i).click();if(n.options[i].ending){assert.equal((await snap()).state.endingId,n.options[i].ending);return true;}assert.equal((await snap()).p.selected,i);assert.equal((await snap()).state.b,null);await page.click('#nextBtn');if(n.options[i].branch){assert.equal((await snap()).state.b.option,i);await resume();}}else await page.click('#nextBtn');}
else if(n.type==='chat'){await page.waitForFunction(()=>[...document.querySelectorAll('.chat-photo')].every(im=>im.complete&&im.naturalWidth>0));if(!chatResumed.has(k+route)){await resume();chatResumed.add(k+route);}const m=n.messages[p.i-1];if(m.options&&p.replies[p.i-1]===undefined){await page.waitForFunction(()=>{const ims=document.querySelectorAll('.chat-photo');return ims.length===2&&[...ims].every(im=>im.complete&&im.naturalWidth>0);});assert((await page.locator('#chat').textContent()).includes('轻点查看照片'));await screenshot('chat-photos-'+(await page.viewportSize()).width);await page.locator('.chat-choice').nth(route).click();assert((await page.locator('#chatBody').textContent()).includes(m.options[route].text));await resume();}else if(p.i<n.messages.length)await page.click('.chat-next');else await page.click('.chat-finish');if(s.c===1&&p.i===5)await screenshot('phone-'+(await page.viewportSize()).width);}
else if(n.type==='task'){if(cancel&&s.c===0&&n.kind==='connect'){await page.click('.cancel-connect');assert.equal((await snap()).state.endingId,'missed');return true;}await solve();}
else throw Error('Unknown node');return true;}
async function run(route,early=false,cancel=false){let steps=0;while(await step(route,early,cancel))assert(steps++<400,'no infinite loop');return (await snap()).state;}
try{
await page.goto(base,{waitUntil:'networkidle'});await screenshot('cover-1440');await page.click('#startBtn');let end=await run(0,true);assert.equal(end.endingId,'missed');assert.equal(end.unlocked,0);assert(!end.collected.includes('好友申请'));await screenshot('early-ending');await resume();checks.push('silence ends in chapter 1 and resumes');
const silenceEnd=JSON.parse(JSON.stringify(end));await page.click('#rewindBtn');let retry=await snap();assert.equal(retry.k,'0:7');assert.equal(retry.p.selected,undefined);assert(!retry.state.flags.silent);assert(retry.state.collected.includes('毯子'));assert(retry.state.endings.includes('missed'));assert(!retry.state.gate&&!retry.state.ended);await resume();await page.locator('.choice').nth(1).click();assert.equal((await snap()).state.endingId,'missed');await page.click('#rewindBtn');assert.equal((await snap()).k,'0:7');await page.locator('.choice').nth(1).click();checks.push('silence retry restores exact unanswered choice repeatedly, preserving earlier puzzle and ending discovery');
await page.evaluate(s=>{delete s.decisions;delete s.decisionOrder;delete s.lastDecision;localStorage.setItem(SAVE_KEY,JSON.stringify(s));},silenceEnd);await page.reload({waitUntil:'networkidle'});await page.click('#continueBtn');await page.click('#rewindBtn');assert.equal((await snap()).k,'0:7');assert(!(await snap()).state.flags.silent);await page.locator('.choice').nth(1).click();checks.push('legacy silence ending resumes at original choice');
await restart();end=await run(0,false,true);assert.equal(end.endingId,'missed');assert(!end.collected.includes('好友申请'));checks.push('cancel friend request also ends');
const cancelEnd=JSON.parse(JSON.stringify(end));await page.click('#rewindBtn');retry=await snap();assert.equal(retry.k,'0:9');assert.equal(retry.node.kind,'connect');assert(retry.state.flags.speak);assert(!retry.p.done);await resume();await page.click('.connect-btn');assert((await snap()).state.collected.includes('好友申请'));assert(!(await snap()).state.ended);await page.evaluate(s=>{delete s.decisions;delete s.decisionOrder;delete s.lastDecision;localStorage.setItem(SAVE_KEY,JSON.stringify(s));},cancelEnd);await page.reload({waitUntil:'networkidle'});await page.click('#continueBtn');await page.click('#rewindBtn');assert.equal((await snap()).k,'0:9');await page.click('.cancel-connect');checks.push('cancel retry and legacy cancel retry return to friend request, not speech or chapter start');
await restart();end=await run(0);assert.equal(end.endingId,'be-yourself');assert.equal(end.c,8);assert(end.endings.includes('missed'));await screenshot('main-ending');await resume();const saved=JSON.stringify((await snap()).state);checks.push('all route A branches reach canonical ending');
fs.writeFileSync(path.join(out,'complete-save.json'),saved);
await page.click('#chapterBtn');assert.equal(await page.locator('.chapter-link').count(),9);assert.equal(await page.locator('.decision-link').count(),12);assert.equal(await page.locator('.decision-link:disabled').count(),0);await screenshot('nodes-1440');await page.setViewportSize({width:390,height:844});await screenshot('nodes-390');await page.setViewportSize({width:1440,height:900});await page.locator('[data-decision="5:54"]').click();await page.click('.decision-review');await ready();assert.equal((await snap()).k,'5:54');assert.equal((await snap()).p.selected,undefined);assert(await page.evaluate(()=>review));await page.locator('.choice').nth(1).click();await page.click('#nextBtn');assert.equal((await snap()).state.b.option,1);await page.click('#exitReview');assert.equal(JSON.stringify((await snap()).state),saved);
await page.click('#chapterBtn');await page.locator('[data-decision="1:1:chat:23"]').click();await page.click('.decision-review');await ready();assert.equal((await snap()).p.i,24);assert.equal((await snap()).p.replies[23],undefined);await page.locator('.chat-choice').nth(1).click();assert((await snap()).state.flags.tease);assert(!(await snap()).state.flags.praise);await ready();await page.click('#exitReview');assert.equal(JSON.stringify((await snap()).state),saved);checks.push('chapter menu lists all 12 decisions; late-chapter and chat node review restore exact cursor without changing main save');
await page.click('#chapterBtn');await page.locator('[data-decision="5:54"]').click();await screenshot('node-confirmation');await page.click('.decision-resume');retry=await snap();assert.equal(retry.k,'5:54');assert.equal(retry.p.selected,undefined);assert(!await page.evaluate(()=>review));assert.equal(retry.state.unlocked,5);assert(!retry.state.flags['accept-help']);assert(!retry.state.flags['gentle-heal']);assert(!retry.state.collected.includes('向日葵'));assert.equal(Object.keys(retry.state.checkpoints).length,6);assert(retry.state.decisionOrder.every(k=>Number(k.split(':')[0])<=5));assert.equal(retry.state.endings.length,2);await resume();await page.click('#chapterBtn');assert(await page.locator('[data-decision="8:4"]').isDisabled());await page.click('#closeModal');await page.locator('.choice').nth(1).click();await page.click('#nextBtn');assert.equal((await snap()).state.b.option,1);await resume();checks.push('main rebranch clears future flags, logs, collection, nodes and checkpoints while preserving endings');
await ready();await page.evaluate(s=>localStorage.setItem(SAVE_KEY,s),saved);await page.reload({waitUntil:'networkidle'});await page.click('#continueBtn');
await page.click('#chapterBtn');await page.locator('.chapter-link').first().click();assert((await snap()).state.gate);await page.click('.gate-start');assert.equal((await snap()).state.collected.length,0);await page.click('#nextBtn');await page.click('#exitReview');assert.equal(JSON.stringify((await snap()).state),saved);await page.click('#chapterBtn');await page.locator('.chapter-link').nth(5).click();await ready();await page.reload({waitUntil:'networkidle'});await page.click('#continueBtn');assert.equal(JSON.stringify((await snap()).state),saved);checks.push('chapter review uses start checkpoint and does not contaminate main save');
await page.click('#endingGallery');assert.equal(await page.locator('.ending-entry:has-text("已读结局")').count(),2);await page.locator('.gallery-link').nth(5).click();await page.waitForFunction(()=>{const i=document.querySelector('.gallery-photo');return i.complete&&i.naturalWidth>0;});await page.click('#closeModal');
await page.setViewportSize({width:390,height:844});await restart();end=await run(1);assert.equal(end.endingId,'be-yourself');checks.push('all route B branches pass on 390px mobile');assert.equal(chaptersSeen.size,9);const expected=await page.evaluate(()=>CHAPTERS.reduce((sum,c)=>sum+c.nodes.reduce((cnt,n)=>cnt+(n.type==='task'?1:0)+(n.options||[]).reduce((s,o)=>s+(o.branch||[]).filter(x=>x.type==='task').length,0),0),0));assert.equal(taskSeen.size,expected,'every main and branch task covered');
await page.click('#chapterBtn');await page.locator('.chapter-link').first().click();await page.click('.gate-start');await page.evaluate(()=>{CHAPTERS[0].nodes[0].text='<img src=x onerror=alert(1)>';render();});assert.equal(await page.locator('#lineText img').count(),0);await page.click('#exitReview');checks.push('safe text rendering');
await page.evaluate(()=>localStorage.setItem(SAVE_KEY,'{broken'));await page.reload({waitUntil:'networkidle'});assert(await page.locator('#continueBtn').isHidden());await page.click('#startBtn');assert(await page.locator('.gate-start').isVisible());checks.push('corrupt save fallback');
const typingContext=await browser.newContext({reducedMotion:'no-preference'});const tp=await typingContext.newPage();tp.on('pageerror',e=>errors.push(e.message));await tp.goto(base,{waitUntil:'networkidle'});await tp.click('#startBtn');await tp.click('.gate-start');await tp.click('#nextBtn');assert.equal(await tp.evaluate(()=>state.n),0,'first click reveals sentence');await tp.click('#nextBtn');assert.equal(await tp.evaluate(()=>state.n),1,'second click advances');await typingContext.close();checks.push('typewriter click reveal, then advance');
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=()=>{throw Error('blocked');};Storage.prototype.getItem=()=>{throw Error('blocked');};});const bp=await blocked.newPage();bp.on('pageerror',e=>errors.push(e.message));await bp.goto(base,{waitUntil:'networkidle'});await bp.click('#startBtn');await bp.click('.gate-start');assert(await bp.locator('#dialogue').isVisible());await blocked.close();checks.push('storage unavailable still playable');assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',chapters:9,tasksCovered:taskSeen.size,choiceRoutes:choiceSeen.size,endings:['missed','be-yourself'],checks,errors},null,2));
}catch(e){await page.screenshot({path:path.join(out,'failure.webp')});throw e;}
})().then(async()=>{if(browser)await browser.close();await new Promise(r=>server.close(r));}).catch(async e=>{console.error(e);if(browser)await browser.close();server.close();process.exitCode=1;});
