// Historical test source; update old chapter/node expectations before use.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('http'),fs=require('fs'),path=require('path');
const root=path.resolve(process.env.GAME_DIR||path.resolve(__dirname,'../..')),out=__dirname;let browser;
const server=http.createServer((req,res)=>{const target=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));const file=target===root?path.join(root,'index.html'):target;if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,buf)=>{if(err){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(buf);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});const saved=JSON.parse(fs.readFileSync(path.join(out,'complete-save.json'),'utf8'));await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle'});await page.evaluate(s=>{state=s;save();render();},saved);
const imagesReady=()=>page.waitForFunction(()=>[...document.querySelectorAll('img')].filter(im=>im.getClientRects().length).every(im=>im.complete&&im.naturalWidth>0));
for(const width of [1440,768,390]){await page.setViewportSize({width,height:width===1440?900:width===768?1024:844});await page.click('#chapterBtn');await page.locator('[data-decision="1:1:chat:23"]').click();await page.click('.decision-review');await imagesReady();const before=await page.evaluate(()=>JSON.stringify(state));for(const photo of ['photo-sunset','photo-toy']){await page.locator('.chat-photo-button').filter({has:page.locator('img[src$="'+photo+'.webp"]')}).click();await imagesReady();assert((await page.locator('.gallery-photo').getAttribute('src')).endsWith(photo+'.webp'));await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>JSON.stringify(state)),before);}assert.equal(await page.evaluate(()=>localStorage.getItem(SAVE_KEY)),JSON.stringify(saved));await page.screenshot({path:path.join(out,'photo-chat-'+width+'.webp')});await page.click('#exitReview');await imagesReady();}
await page.click('#chapterBtn');await page.locator('[data-decision="1:2"]').click();await page.click('.decision-review');await page.locator('.choice').nth(1).click();await page.click('#nextBtn');await page.click('#nextBtn');await imagesReady();assert.equal(await page.evaluate(()=>current().photo),'photo-toy-received');const at=await page.evaluate(()=>JSON.stringify(state));await page.click('.puzzle-photo-button');await imagesReady();assert((await page.locator('.gallery-photo').getAttribute('src')).endsWith('photo-toy-received.webp'));await page.click('#closeModal');assert.equal(await page.evaluate(()=>JSON.stringify(state)),at);await page.locator('[data-answer="1"]').click();assert(!await page.evaluate(()=>prog().done));await page.locator('[data-answer="0"]').click();assert(await page.evaluate(()=>prog().done));
const tasks=await page.evaluate(()=>CHAPTERS.flatMap((c,ci)=>c.nodes.flatMap((n,ni)=>[...(n.type==='task'?[{c:ci,n:ni,b:null}]:[]),...(n.options||[]).flatMap((o,oi)=>(o.branch||[]).flatMap((v,vi)=>v.type==='task'?[{c:ci,n:ni,b:{option:oi,cursor:vi}}]:[]))])));
for(const t of tasks){await page.evaluate(t=>{state={...fresh(),...t,gate:false};render();},t);await imagesReady();assert.equal(await page.locator('#task img').count(),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',zoom:'chat and puzzle images preserve cursor and main save',viewports:[1440,768,390],illustratedTasks:tasks.length,errors},null,2));})().then(async()=>{await browser.close();server.close();}).catch(async e=>{console.error(e);if(browser)await browser.close();server.close();process.exitCode=1;});
